apiVersion: v1
kind: Service
metadata:
  name: qwen2-5-0-5b
  namespace: rhaiis-namespace
spec:
  selector:
    app: qwen2-5-0-5b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http