apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-3-2-3b-instruct-q8
  namespace: rhaiis-namespace
  labels:
    app: llama-3-2-3b-instruct-q8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-3-2-3b-instruct-q8
  template:
    metadata:
      labels:
        app: llama-3-2-3b-instruct-q8
    spec:
      imagePullSecrets:
        - name: docker-secret
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: llama-3-2-3b-instruct-q8
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "16Gi"
      serviceAccountName: default
      containers:
        - name: llama-3-2-3b-instruct-q8
          image: 'registry.redhat.io/rhaiis/vllm-cuda-rhel9@sha256:a6645a8e8d7928dce59542c362caf11eca94bb1b427390e78f0f8a87912041cd'
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: hf-secret
          env:
            - name: VLLM_SERVER_DEV_MODE
              value: '1'
            - name: HUGGING_FACE_HUB_TOKEN
              value: '$HF_TOKEN'
            - name: HF_HUB_OFFLINE
              value: '0'
            - name: HF_HOME
              value: /opt/app-root/src/.cache
            - name: MODEL_NAME
              value: "meta-llama/Llama-3.2-3B-Instruct-Q8"
          command:
            - python
            - '-m'
            - vllm.entrypoints.openai.api_server
          args:
            - '--port=8000'
            - '--served-model-name=meta-llama/Llama-3.2-3B-Instruct-Q8'
            - '--tensor-parallel-size=1'
            - '--model=/opt/app-root/src/.cache/hub/models--meta-llama_Llama-3.2-3B-Instruct-Q8/Llama-3.2-3B-Instruct-Q8_0.gguf'
            - '--load-format=gguf'
            - '--quantization=gguf'
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: '8'
              memory: 32Gi
              nvidia.com/gpu: '1'
            requests:
              cpu: '2'
              memory: 16Gi
              nvidia.com/gpu: '1'
          volumeMounts:
            - name: model-volume
              mountPath: /opt/app-root/src/.cache
            - name: shm
              mountPath: /dev/shm
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 120
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: g6e-gpu
          operator: Exists