apiVersion: v1
kind: Service
metadata:
  name: llama-3-2-3b-instruct-q8
  namespace: rhaiis-namespace
spec:
  selector:
    app: llama-3-2-3b-instruct-q8
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http